spring:
  config:
    name: staging
    profiles:
      active: staging

  properties:
    hibernate:
      format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/farmbusiness?createDatabaseIfNotExist=true
    username: root
    password: rootadmin

  jpa:
    defer-datasource-initialization: true
    show-sql: true

  mvc:
    log-request-details: true
    static-path-pattern: /static/**

  resources:
    static-locations: classpath:/static/

server:
  error:
    include-stacktrace: never

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR

jwt:
  secret: 50b73bb0-38b1-11ee-be56-0242ac120002
  expiration: 999999

