spring:
  config:
    name: staging
    profiles:
      active: staging

  properties:
    hibernate:
      format_sql: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    defer-datasource-initialization: true
      show-sql: true

server:
  error:
    include-stacktrace: never

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR

jwt:
  secret: ${JWT_SECRET}
  expiration: 999999

