spring:
  config:
    name: prod
    profiles:
      active: prod

  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    port: ${DATABASE_PORT}

  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    default-property-inclusion: non_ null

server:
  ssl:
    enabled: true
    key-store: /folder/file.jks
    key-store-password: 123456
    keyStoreType: jks
    key-alias: somealias

jwt:
  secret: ${JWT_SECRET}
  expiration: 999999