spring:
  properties:
    hibernate:
      format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/farmbusiness?createDatabaseIfNotExist=true
    username: farm
    password: farmadmin

  jpa:
    defer-datasource-initialization: true
    show-sql: true

  mvc:
    log-request-details: true
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true

  resources:
    static-locations: classpath:/static/

server:
  error:
    include-stacktrace: never

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR

jwt:
  secret: 123456
  expiration: 999999